"""
code to plot maps of snow covered area for individual years from summary lists generated by catchment_evalutation.py
"""

import numpy as np
import matplotlib.pylab as plt
import netCDF4 as nc
import copy



def plot_swe(run_id, met_inp, which_model, hydro_years_to_take, catchment, output_dem, origin, model_swe_sc_threshold, mask_file, dsc_snow_output_folder,
                  plot_folder):

    bounding = 'moving'
    lats = np.linspace(48e5, 50e5, 365) # asssume plot is 5e5 high, 4e5 wide    lats = np.linspace(47e5, 52e5, 365) # asssume plot is 5e5 high, 4e5 wide
    lons = np.linspace(11e5, 12e5, 365)#    lons = np.linspace(10e5, 15e5, 365)
    camera_motion = [lats, lons]

    plt.rcParams.update({'font.size': 14})
    plt.rcParams.update({'axes.titlesize' : 14})


    # bin_edges = [-0.001, 30, 60, 90, 120, 180, 270, 360]  # use small negative number to include 0 in the interpolation

    for i, year_to_take in enumerate(hydro_years_to_take):
        modis_mask = np.load(mask_file)
        fig1 = plt.figure(figsize=[8, 6])
        print('loading data for year {}'.format(year_to_take))
        nc_file = nc.Dataset(model_output_folder + '/snow_out_{}_{}_{}_{}_{}_{}.nc'.format(met_inp, which_model, catchment, output_dem, run_id, year_to_take), 'r')
        nztm_dem = nc_file.variables['elevation'][:]
        x_centres= nc_file.variables['easting'][:]
        y_centres = nc_file.variables['northing'][:-116]
        out_dt = nc.num2date(nc_file.variables['time'][:], nc_file.variables['time'].units)#, only_use_cftime_datetimes=False,                             only_use_python_datetimes=True
        for i in range(nc_file.variables['swe'].shape[0]):

            swe = np.log(nc_file.variables['swe'][i,:-116, :])
            swe[np.isinf(swe)]= 0 # take for NZ
            swe[modis_mask == False] = np.nan

            CS1 = plt.pcolormesh(x_centres, y_centres, swe,cmap=copy.copy(plt.cm.get_cmap('viridis')),vmin=1.61,vmax=8.52)#levels=bin_edges, extend='max'
            #CS1.cmap.set_bad('grey')
            #CS1.cmap.set_under('grey')
            #CS1.cmap.set_under('grey')
            plt.gca().set_aspect('equal')
            # plt.imshow(modis_scd, origin=0, interpolation='none', vmin=0, vmax=365, cmap='magma_r')
            plt.xticks([])
            plt.yticks([])
            cbar = plt.colorbar(CS1, ticks=np.log([5, 50, 500, 5000]))
            cbar.set_ticklabels([5, 50, 500, 5000])
            cbar.set_label('Snow water equivalent (mm w.e.)', rotation=90)
            plt.xticks(np.arange(12e5, 21e5, 2e5))
            plt.yticks(np.arange(48e5, 63e5, 2e5))
            if bounding=='moving':
                plt.ylim((camera_motion[0][i],camera_motion[0][i]+4e5))
                plt.xlim((camera_motion[1][i],camera_motion[1][i]+5e5))
            plt.ticklabel_format(axis='both', style='sci', scilimits=(0, 0))
            plt.ylabel('NZTM northing')
            plt.xlabel('NZTM easting')
            plt.title('SWE {}'.format(out_dt[i]))
            plt.tight_layout()

            plt.savefig(plot_folder + '/SWE model {} thres{} {} {} {} {}.png'.format(year_to_take, model_swe_sc_threshold, run_id,met_inp, which_model,i), dpi=150)
            # plt.show()
            plt.clf()

if __name__ == '__main__':

    years_to_take = np.arange(2001, 2020 + 1)  # [2013 + 1]  # range(2001, 2013 + 1)

    run_id = 'cl09_default_ros'
    met_inp = 'nzcsm7-12'  # identifier for input meteorology
    which_model = 'clark2009'  # 'clark2009'  # 'dsc_snow'  # string identifying the model to be run. options include 'clark2009', 'dsc_snow' # future will include 'fsm'
    # time and grid extent options
    hydro_years_to_take = np.arange(2018, 2020 + 1)
    catchment = 'NZ'  # string identifying the catchment to run. must match the naming of the catchment mask file
    output_dem = 'nz_dem_250m'  # string identifying output DEM

    origin = 'bottomleft' # origin of model domain. 'bottomleft' for python otf
    model_swe_sc_threshold = 30  # threshold for treating a grid cell as snow covered (mm w.e)
    mask_file = '/nesi/project/niwa00004/jonoconway/modis_mask_hy2018_2020_landpoints.npy'  # masked for any ocean/inland water cells in modis record + elevation >0
    output_folder = '/nesi/nobackup/niwa00004/jonoconway/snow_sims_nz/nzcsm/daily_plots'
    model_output_folder = '/nesi/nobackup/niwa00004/jonoconway/snow_sims_nz/nzcsm'

    plot_swe(run_id, met_inp, which_model, hydro_years_to_take, catchment, output_dem, origin, model_swe_sc_threshold, mask_file, model_output_folder,
                  output_folder)